### Offset request
GET {{host}}/api/demo/users/offset?limit=5&page=10000

### Cursor request (first)
GET {{host}}/api/demo/users/cursor?limit=5

> {%
    const token = response.body.next;
    client.global.clear("token");
    client.global.set("token", token);

    // client.log("token =", token);
%}

### Cursor request (second)
GET {{host}}/api/demo/users/cursor?limit=5&next={{token}}

> {%
    const token = response.body.prev;
    client.global.clear("token");
    client.global.set("token", token);
%}

### Cursor request (third)
GET {{host}}/api/demo/users/cursor?limit=5&prev={{token}}


### Cursor with offset request (first)
GET {{host}}/api/demo/users/hybrid?limit=5&page=50000

> {%
    const token = response.body.next;
    client.global.clear("token");
    client.global.set("token", token);
%}

### Cursor with offset request (second)
GET {{host}}/api/demo/users/hybrid?limit=5&next={{token}}

> {%
    const token = response.body.prev;
    client.global.clear("token");
    client.global.set("token", token);
%}

### Cursor with offset request (third)
GET {{host}}/api/demo/users/hybrid?limit=5&prev={{token}}


